export const FILE_INPUT_ID = "fileSelector";
export const EDITOR_CANVAS_ID = "editorCanvas";
export const CANVAS_WIDTH = 1440; // 15 inches converted to pixels
export const CANVAS_HEIGHT = 960; // 10 inches converted to pixels
export const CONTROL_BAR = "controlBar";
export const ZOOM_IN_BTN = "zoomIn";
export const ZOOM_OUT_BTN = "zoomOut";
export const SHIFT_UP_BTN = "shiftUp";
export const SHIFT_DOWN_BTN = "shiftDown";
export const SHIFT_RIGHT_BTN = "shiftRight";
export const SHIFT_LEFT_BTN = "shiftLeft";
export const PRINT_BTN = "print";
export const IMPORT_BTN = "importBtn";
export const SUBMIT_BTN = "submitImage";
export const JSON_VIEW = "jsonView";